=== K-Felk/mod-kb-ebsco-java/ramls/types/resources/resourceIncludedItem.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Resource object schema for an included item",
  "description": "Resource object schema for an included item",
  "javaType": "org.folio.rest.jaxrs.model.ResourceIncludedItem",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier of an included item",
      "example": "1440285"
    },
    "type": {
      "type": "string",
      "description": "Type of an included item",
      "enum": [
        "providers",
        "package",
        "titles"
      ],
      "example": "providers"
    },
    "attributes": {
      "type": "object",
      "description": "Resource included item attributes",
      "$ref": "resourceIncludedItemAttributes.json"
    },
    "relationships": {
      "type": "object",
      "description": "Resource included item relationships",
      "$ref": "resourceRelationships.json"
    }
  }
}

=== K-Felk/mod-kb-ebsco-java/src/test/resources/responses/kb-ebsco/providers/expected-provider-by-id-for-resource.json
{
  "id": "583",
  "type": "providers",
  "attributes": {
    "name": "ABC-CLIO",
    "packagesTotal": 34,
    "packagesSelected": 1,
    "supportsCustomPackages": false,
    "proxy": {
      "id": "Proxy-ID-123",
      "inherited": true
    }
  },
  "relationships": {
    "packages": {
      "meta": {
        "included": false
      }
    }
  }
}
